In [2]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori

In [3]:
dataset=[['사과','치즈','생수'],
['생수','호두','치즈','고등어'],
['수박','사과','생수'],
['생수','호두','치즈','옥수수']]

In [4]:
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_) #위에서 나온걸 보기 좋게 데이터프레임으로 변경

In [5]:
frequent_itemsets = apriori(df, min_support=0.5, use_colnames=True)
frequent_itemsets

   support      itemsets
0     0.50          (사과)
1     1.00          (생수)
2     0.75          (치즈)
3     0.50          (호두)
4     0.50      (사과, 생수)
5     0.75      (치즈, 생수)
6     0.50      (호두, 생수)
7     0.50      (호두, 치즈)
8     0.50  (호두, 치즈, 생수)

In [6]:
from mlxtend.frequent_patterns import association_rules
association_rules(frequent_itemsets, metric="confidence", min_threshold=0.3) 
# 신뢰도가 0.3인 항목만 보기

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(사과),(생수),0.50,1.00,0.50,1.000000,1.000000,0.000,inf
1,(생수),(사과),1.00,0.50,0.50,0.500000,1.000000,0.000,1.0
2,(치즈),(생수),0.75,1.00,0.75,1.000000,1.000000,0.000,inf
3,(생수),(치즈),1.00,0.75,0.75,0.750000,1.000000,0.000,1.0
4,(호두),(생수),0.50,1.00,0.50,1.000000,1.000000,0.000,inf
5,(생수),(호두),1.00,0.50,0.50,0.500000,1.000000,0.000,1.0
6,(호두),(치즈),0.50,0.75,0.50,1.000000,1.333333,0.125,inf
7,(치즈),(호두),0.75,0.50,0.50,0.666667,1.333333,0.125,1.5
8,"(호두, 치즈)",(생수),0.50,1.00,0.50,1.000000,1.000000,0.000,inf
9,"(호두, 생수)",(치즈),0.50,0.75,0.50,1.000000,1.333333,0.125,inf
10,"(치즈, 생수)",(호두),0.75,0.50,0.50,0.666667,1.333333,0.125,1.5
11,(호두),"(치즈, 생수)",0.50,0.75,0.50,1.000000,1.333333,0.125,inf
12,(치즈),"(호두, 생수)",0.75,0.50,0.50,0.666667,1.333333,0.125,1.5
13,(생수),"(호두, 치즈)",1.00,0.50,0.50,0.500000,1.000000,0.000,1.0

항상도(lift)
1 보다 작은 경우 : 우연적 기회보다 높은 확률
1 인 경우 : 독립
1 보다 큰 경우 : 우연적 기회보다 낮은 확률